atoum/urls.py
from django.urls import path

from .views import (
    AssortmentAutocompleteView,
    AssortmentDetailView,
    AssortmentIndexView,
    CategoryAutocompleteView,
    CategoryDetailView,
    CategoryIndexView,
    ConsumableDetailView,
    ConsumableIndexView,
    DashboardView,
    DummyView,
    GlobalSearchView,
    ProductAutocompleteView,
    ProductDetailView,
    ProductIndexView,
    RecursiveTreeView,
    ShoppinglistDetailView,
    ShoppinglistIndexView,
    ShoppinglistToggleSelectionView,
    ShoppinglistManageProductView,
)


app_name = "atoum"


urlpatterns = [
    path("", DashboardView.as_view(), name="dashboard"),

    # Full recursive tree of everything
    path("tree/", RecursiveTreeView.as_view(), name="tree"),

    path(
        "consumables/",
        ConsumableIndexView.as_view(),
        name="consumable-index"
    ),
    path(
        "assortments/",
        AssortmentIndexView.as_view(),
        name="assortment-index"
    ),
    path(
        "categories/",
        CategoryIndexView.as_view(),
        name="category-index"
    ),
    path(
        "products/",
        ProductIndexView.as_view(),
        name="product-index"
    ),
    path(
        "consumables/<slug:slug>/",
        ConsumableDetailView.as_view(),
        name="consumable-detail"
    ),
    path(
        "consumables/<slug:consumable_slug>/<slug:assortment_slug>/",
        AssortmentDetailView.as_view(),
        name="assortment-detail"
    ),
    path(
        (
            "consumables/<slug:consumable_slug>/<slug:assortment_slug>/"
            "<slug:category_slug>/"
        ),
        CategoryDetailView.as_view(),
        name="category-detail"
    ),
    path(
        (
            "consumables/<slug:consumable_slug>/<slug:assortment_slug>/"
            "<slug:category_slug>/<slug:product_slug>/"
        ),
        ProductDetailView.as_view(),
        name="product-detail"
    ),

    # TODO: These are temporarily dummy views enabled to allow reversing until
    # they are implemented
    path(
        "brands/<slug:slug>/",
        DummyView.as_view(),
        name="brand-detail"
    ),

    # Shopping list parts
    path(
        "shopping/",
        ShoppinglistIndexView.as_view(),
        name="shopping-list-index"
    ),
    # TODO: Rename with "inventory" instead
    path(
        "shopping/close-selection/",
        ShoppinglistToggleSelectionView.as_view(),
        name="shopping-list-close-selection"
    ),
    path(
        "shopping/<int:pk>/",
        ShoppinglistDetailView.as_view(),
        name="shopping-list-detail"
    ),
    # TODO: Rename with "inventory" instead
    path(
        "shopping/<int:pk>/open-selection/",
        ShoppinglistToggleSelectionView.as_view(),
        name="shopping-list-open-selection"
    ),
    path(
        "shopping/<int:pk>/product/<int:product_id>/",
        ShoppinglistManageProductView.as_view(),
        name="shopping-list-product"
    ),

    # Autocomplete views for various models, only for staff users
    path(
        "autocomplete/assortments/",
        AssortmentAutocompleteView.as_view(),
        name="autocomplete-assortments",
    ),
    path(
        "autocomplete/categories/",
        CategoryAutocompleteView.as_view(),
        name="autocomplete-categories",
    ),
    path(
        "autocomplete/products/",
        ProductAutocompleteView.as_view(),
        name="autocomplete-products",
    ),

    # Search engine form and results
    path("search/", GlobalSearchView.as_view(), name="search-results"),
]

atoum/forms/shopping.py
from django import forms

from dal import autocomplete

from ..models import Product, Shopping, ShoppingItem


class ProductBreadcrumbChoiceField(forms.ModelChoiceField):
    """
    Customize product model choice field.
    """
    def label_from_instance(self, obj):
        """
        Display product parenting crumbs of a choice option.

        This label should be the same returned from
        ``ProductAutocompleteView.get_selected_result_label()``.
        """
        return obj.parenting_crumbs_html()


class ShoppingAdminForm(forms.ModelForm):
    class Meta:
        fields = "__all__"
        model = Shopping


class ShoppingItemInlineForm(autocomplete.FutureModelForm):
    class Meta:
        fields = "__all__"
        model = ShoppingItem

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        # Override Product model form field to customize option label and enable
        # DAL autocompletion
        self.fields["product"] = ProductBreadcrumbChoiceField(
            queryset=Product.objects.all().select_related(
                "category",
                "category__assortment",
                "category__assortment__consumable"
            ),
            required=True,
            blank=False,
            widget=autocomplete.ModelSelect2(
                url="atoum:autocomplete-products",
                attrs={"data-html": True},
            ),
        )

atoum/views/shopping.py
from django.conf import settings
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import RedirectURLMixin
from django.shortcuts import get_object_or_404
from django.http import HttpResponseRedirect, HttpResponseBadRequest, QueryDict
from django.views import View
from django.views.generic import TemplateView
from django.views.generic import ListView
from django.urls import reverse
from django.utils.translation import gettext_lazy as _

from ..models import Product, Shopping, ShoppingItem
from .mixins import AtoumBreadcrumMixin


class ShoppinglistIndexView(AtoumBreadcrumMixin, LoginRequiredMixin, ListView):
    """
    List of Shopping lists
    """
    model = Shopping
    template_name = "atoum/shopping/index.html"
    paginate_by = settings.ATOUM_SHOPPINGLIST_PAGINATION
    crumb_title = _("Shopping lists")
    crumb_urlname = "atoum:shopping-list-index"

    def get_queryset(self):
        # Append 'done' field over the common ordering fields so the undone lists
        # have higher priority
        ordering = ["done"] + self.model.COMMON_ORDER_BY
        return self.model.objects.order_by(*ordering)

    @property
    def crumbs(self):
        return [
            (
                ShoppinglistIndexView.crumb_title,
                reverse(ShoppinglistIndexView.crumb_urlname)
            ),
        ]


class ShoppinglistDetailView(AtoumBreadcrumMixin, LoginRequiredMixin, TemplateView):
    """
    Shopping list detail
    """
    model = Shopping
    template_name = "atoum/shopping/detail.html"
    context_object_name = "shopping_object"
    crumb_title = None  # No usage since title depends from object
    crumb_urlname = "atoum:shopping-list-detail"

    @property
    def crumbs(self):
        return [
            (
                ShoppinglistIndexView.crumb_title,
                reverse(ShoppinglistIndexView.crumb_urlname)
            ),
            (
                str(self.object),
                reverse(self.crumb_urlname, kwargs={
                    "pk": self.object.id,
                })
            ),
        ]

    def get_object(self):
        """
        Get the Shopping list object
        """
        return get_object_or_404(self.model, pk=self.kwargs.get("pk"))

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context.update({
            "object": self.object,
            self.context_object_name: self.object,
        })

        return context

    def get(self, request, *args, **kwargs):
        self.object = self.get_object()

        return super().get(request, *args, **kwargs)


class ShoppinglistToggleSelectionView(LoginRequiredMixin, RedirectURLMixin, View):
    """
    View to open or close a Shopping list for product selection.

    For opening it requires the shopping ID in "pk" argument from URL. For closing it
    does not require anything and just blindly purge the session variable.
    """
    model = Shopping
    raise_exception = True

    def get_object(self):
        """
        Get the Shopping list object
        """
        return get_object_or_404(self.model, pk=self.kwargs.get("pk"))

    def get(self, request, *args, **kwargs):
        self.next_page = reverse("atoum:dashboard")

        url = self.get_success_url()

        # If shopping id is given add it as opened in session
        if "pk" in self.kwargs:
            self.object = self.get_object()
            self.request.session["atoum_shopping_inventory"] = self.object.id
        # Else assume we have to close any opened shopping from session
        else:
            del self.request.session["atoum_shopping_inventory"]

        return HttpResponseRedirect(url)


class ShoppinglistManageProductView(LoginRequiredMixin, TemplateView):
    """
    View to add, edit or remove a product of a Shopping list.

    This has been done for usage from htmx so it won't return a proper HTML page
    document.
    """
    model = Shopping
    template_name = "atoum/shopping/manage_inventory.html"
    operation_name = None
    raise_exception = True

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context.update({
            "shopping_object": self.object,
            "product": self.product,
            "shopping_item": self.shopping_item,
            "operation": self.operation_name,
        })

        return context

    def parse_quantity(self):
        """
        Parse given quantity from POST arguments.

        Returns:
            integer: Parsed quantity if it is a valid integer else returns a null
                value.
        """
        try:
            quantity = int(self.request.POST.get("quantity", 1))
        except ValueError:
            return None

        if not quantity or quantity < 1:
            quantity = 0

        return quantity

    def delete_shopping_item(self):
        """
        Remove the given product item from the Shopping list.

        Returns:
            dict: Return dict with some values (id and quantity) from deleted object.
        """
        obj = get_object_or_404(
            ShoppingItem,
            shopping=self.object,
            product=self.product
        )

        # Memorize useful data from object because template still use it
        memorized = {"id": obj.id, "quantity": obj.quantity}
        # Finally deletes the item
        obj.delete()
        self.operation_name = "deletion"

        return memorized

    def update_or_create_shopping_item(self, quantity):
        """
        Update or create the ShoppingItem object and possibly set its quantity if not
        null.

        Arguments:
            quantity (integer): The quantity to apply on object. It must be a greater
                or equal to 1 else it would not do nothing (except getting existing
                item).

        Returns:
            atoum.models.ShoppingItem: Return the existing or created object if
                quantity is greater or equal to 1. Else it returns the item object if
                it already exists or a null value if it does not exists yet.
        """
        try:
            obj = ShoppingItem.objects.filter(
                shopping=self.object,
                product=self.product
            ).get()
        except ShoppingItem.DoesNotExist:
            if quantity:
                obj = ShoppingItem(
                    shopping=self.object,
                    product=self.product,
                    quantity=quantity
                )
                obj.full_clean()
                obj.save()
                self.operation_name = "addition"
            else:
                obj = None
        else:
            if quantity:
                obj.quantity = quantity
                obj.full_clean()
                obj.save()
                self.operation_name = "edition"

        return obj

    def patch_shopping_item(self, done=None):
        """
        Update attribute ``done`` of the Shopping item.
        """
        if done is None:
            return

        obj = get_object_or_404(
            ShoppingItem,
            shopping=self.object,
            product=self.product
        )

        # NOTE: We can use the update() method instead
        obj.done = done
        obj.save()

        self.object.update_shopping_done()

        self.operation_name = "patch_field_done"

        return obj

    def patch(self, request, *args, **kwargs):
        """
        PATCH verb allows to edit the ``done`` state.
        """
        self.object = get_object_or_404(self.model, pk=self.kwargs.get("pk"))
        self.product = get_object_or_404(Product, pk=self.kwargs.get("product_id"))

        data = QueryDict(self.request.body)

        done_value = (
            data.get("done") == "true"
            if data.get("done", None)
            else None
        )
        # Done field value is mandatory
        if done_value is None:
            return HttpResponseBadRequest()

        self.shopping_item = self.patch_shopping_item(done=done_value)

        return self.render_to_response(self.get_context_data(**kwargs))

    def delete(self, request, *args, **kwargs):
        """
        DELETE verb allows for deletion of an existing product item from a shopping
        list.

        Response will only contains the HTML for product controls for a creation.
        """
        self.object = get_object_or_404(self.model, pk=self.kwargs.get("pk"))
        self.product = get_object_or_404(Product, pk=self.kwargs.get("product_id"))

        self.shopping_item = self.delete_shopping_item()

        return self.render_to_response(self.get_context_data(**kwargs))

    def post(self, request, *args, **kwargs):
        """
        POST verb allows for creation or edition of a product item from a shopping list.

        If product is already an item of shopping list it is an edition and posted
        quantity will replace the previous value.

        Else if product is not in shopping list yet it is a creation and quantity will
        be set from posted value.

        Negative or null quantity is not allowed, it will return a HTTP 400 response.

        Response will contains the HTML for product controls and possibly the new item
        row to append to the shopping list component in case of a creation.
        """
        self.object = get_object_or_404(self.model, pk=self.kwargs.get("pk"))
        self.product = get_object_or_404(Product, pk=self.kwargs.get("product_id"))

        quantity = self.parse_quantity()
        if quantity is None:
            return HttpResponseBadRequest()

        # Proceed to operation
        self.shopping_item = self.update_or_create_shopping_item(quantity)
        return self.render_to_response(self.get_context_data(**kwargs))

    def get(self, request, *args, **kwargs):
        """
        GET verb is not supported.
        """
        return HttpResponseBadRequest()

atoum/templates/atoum/shopping/detail.html
{% extends "atoum/base.html" %}
{% load atoum i18n smart_image %}
{% block header-title %}{{ shopping_object }} - {{ block.super }}{% endblock header-title %}

{% block title-content %}{% spaceless %}
    <p class="mb-0">
        <small class="text-body-secondary"><i class="bi bi-cart4"></i> {% translate "Shopping list" %}&nbsp;:</small>
    </p>

    <h1>{{ shopping_object }}</h1>
{% endspaceless %}{% endblock title-content %}

{% block page-submenu %}
<div class="page-submenu">
    {% if request.user.is_staff %}
        <div class="manage-object dropdown">
            <button class="btn btn-primary dropdown-toggle" type="button"
                    data-bs-toggle="dropdown" aria-expanded="false">
                <i class="bi bi-gear"></i><span class="visually-hidden"> {% translate "Manage" %}</span>
            </button>

            <ul class="dropdown-menu">
                <li>
                    <a href="{% url "admin:atoum_shopping_change" object_id=shopping_object.id %}"
                        class="dropdown-item">
                        <small class="me-3"><i class="bi bi-pencil text-primary"></i> {% translate "Change" %}</small>
                    </a>
                </li>
                <li>
                    <a href="{% url "admin:atoum_shopping_delete" object_id=shopping_object.id %}"
                        class="dropdown-item">
                        <small class="me-3"><i class="bi bi-trash3 text-danger"></i> {% translate "Delete" %}</small>
                    </a>
                </li>
            </ul>
        </div>
    {% endif %}
</div>
{% endblock page-submenu %}

{% block app_content %}{% spaceless %}
    <div class="shopping-detail mt-3">
        <div class="head mb-4 d-flex justify-content-between">
            <div class="flex-grow-1 p-2">
                <p class="h5">{% translate "Planned for" %} {{ shopping_object.planning|date:"l d F Y"|capfirst }}

                <p class="pt-1">
                    <small><span id="shopping-detail-{{ shopping_object.id }}-status">
                    {% include "atoum/shopping/partials/list_status.html" with shopping_inventory=shopping_inventory shopping_object=shopping_object only %}
                    </span></small>
                </p>
            </div>

            {% if not shopping_inventory or shopping_inventory.id != shopping_object.id %}
            <p class="controls">
                <a href="{% url "atoum:shopping-list-open-selection" pk=shopping_object.id %}"
                   class="btn btn-outline-primary">
                    <i class="bi bi-plus-lg"></i> {% translate "Add new products" %}
                </a>
            </p>
            {% endif %}
        </div>

        {% with shopping_items=shopping_object.get_items %}
            {% if shopping_items %}
                <div class="shopping-items list-group">
                    {% for item in shopping_items %}
                        <span id="shopping-detail-{{ shopping_object.id }}-item-{{ item.id }}"
                               class="item to-bump list-group-item d-flex gap-2 justify-content-between">
                            <input class="form-check-input flex-shrink-0"
                                   name="done"
                                   type="checkbox"
                                   value=""
                                   autocomplete="off"
                                   hx-target="#shopping-detail-{{ shopping_object.id }}-status"
                                   hx-vals='js:{done:event.target.checked}'
                                   hx-patch="{% url "atoum:shopping-list-product" pk=shopping_object.id product_id=item.product.id %}"
                                   {% if item.done %} checked{% endif %}>

                            <span class="flex-fill">
                                <span class="title">{{ item.product.title }}</span>
                                <small class="d-block text-body-secondary">{{ item.product.parenting_crumbs_html }}</small>
                            </span>

                            <div class="controls mb-3" style="flex: 1 0 160px; max-width: 160px">
                                {% product_shopping_controls item.product shopping=shopping_object %}
                            </div>
                        </span>
                    {% endfor %}
                </div>
            {% else %}
                <p class="empty p-3 h4 fst-italic text-center">{% translate "No products yet." %}</p>
            {% endif %}
        {% endwith %}
    </div>
{% endspaceless %}{% endblock app_content %}

{% block body-javascript-extra %}
<script>
// On content load from a request, apply css class to parent for highlight bump
document.body.addEventListener("htmx:afterOnLoad", function(evt) {
    let row = htmx.closest(evt.target, "span");
    if(row) {
        htmx.addClass(row, "bump");
        // Use a delay so the animation has the time to finish
        htmx.removeClass(row, "bump", 1200);
    }
});
</script>
{% endblock body-javascript-extra %}

atoum/templates/atoum/shopping/index.html
{% extends "atoum/base.html" %}
{% load i18n %}
{% block header-title %}{% translate "Shopping list" %} - {{ block.super }}{% endblock header-title %}

{% block title-content %}{% spaceless %}
    <h1>
        <i class="bi bi-cart4"></i>
        {% translate "Shopping lists" %}
    </h1>
{% endspaceless %}{% endblock title-content %}

{% block page-submenu %}
    <div class="page-submenu">
        {% if request.user.is_staff %}
            <div class="manage-object dropdown">
                <button class="btn btn-primary dropdown-toggle" type="button"
                        data-bs-toggle="dropdown" aria-expanded="false">
                    <i class="bi bi-gear"></i><span class="visually-hidden"> {% translate "Manage" %}</span>
                </button>
                <ul class="dropdown-menu">
                    <li>
                        <a href="{% url "admin:atoum_shopping_add" %}"
                            class="dropdown-item">
                            <small class="me-3"><i class="bi bi-plus-lg text-success"></i> {% translate "Add a new Shopping list" %}</small>
                        </a>
                    </li>
                </ul>
            </div>
        {% endif %}
    </div>
{% endblock page-submenu %}

{% block app_content %}{% spaceless %}
    <div class="shoppinglist-index mt-3">
        <div class="shoppinglists row">
            {% for shopping in object_list %}
            <div class="item col-12 col-md-6 col-lg-4 pb-4">
                <div class="card{% if shopping.done %} opacity-75{% else %} border-primary{% endif %}">
                    <div class="card-body">
                        <h2 class="card-title h4">
                            <small class="sm-3 lh-1">
                                {% include "atoum/shopping/partials/list_status.html" with shopping_inventory=shopping_inventory.obj shopping_object=shopping only %}
                            </small><br>
                            <span class="title">{{ shopping }}</span>
                        </h2>
                        <div class="card-text">
                            <p>{% translate "Planned for" %} {{ shopping.planning|date:"l d F Y"|capfirst }}</p>
                            <p class="text-end">
                                <a class="btn{% if shopping.done %} btn-secondary{% else %} btn-primary{% endif %}"
                                   href="{{ shopping.get_absolute_url }}">
                                   {% translate "Show" %}
                                </a>
                            </p>
                        </div>
                    </div>
                </div>
            </div>
            {% empty %}
                <div class="empty">
                    <p><em>{% translate "No shopping list yet." %}</em></p>
                </div>
            {% endfor %}
        </div>
    </div>
{% endspaceless %}{% endblock app_content %}

atoum/templates/atoum/shopping/manage_inventory.html
{% load atoum i18n %}{% spaceless %}
    {% if operation == "addition" or operation == "edition" %}
        {% product_shopping_controls product shopping=shopping_object %}

        {% comment %}Append or edit row from possible opened shopping inventory{% endcomment %}
        {% if shopping_inventory and shopping_inventory.id == shopping_object.id %}
            <template>
                {% include "atoum/shopping/partials/opened_list_item.html" with shopping_inventory=shopping_inventory item=shopping_item htmx_swap=True operation=operation only %}
            </template>
        {% endif %}
    {% elif operation == "deletion" %}
        {% product_shopping_controls product shopping=shopping_object %}

        {% comment %}Remove row from possible opened shopping inventory{% endcomment %}
        {% if shopping_inventory and shopping_inventory.id == shopping_object.id %}
            <template>
                <div id="shopping-inventory-{{ shopping_inventory.id }}-item-{{ shopping_item.id }}"
                     hx-swap-oob="delete"></div>
            </template>
        {% endif %}

        {% comment %}Delete row from shopping detail{% endcomment %}
        <template>
            {% if shopping_object %}
                <div id="shopping-detail-{{ shopping_object.id }}-item-{{ shopping_item.id }}"
                     hx-swap-oob="delete"></div>
            {% elif shopping_inventory %}
                <div id="shopping-detail-{{ shopping_inventory.id }}-item-{{ shopping_item.id }}"
                     hx-swap-oob="delete"></div>
            {% endif %}
        </template>
    {% elif operation == "patch_field_done" %}
        {% comment %}Update status from Shopping detail{% endcomment %}
        {% if shopping_object %}
            {% include "atoum/shopping/partials/list_status.html" with shopping_inventory=shopping_inventory shopping_object=shopping_object only %}
        {% endif %}

        {% comment %}Edit item status from possible opened shopping inventory{% endcomment %}
        {% if shopping_inventory and shopping_inventory.id == shopping_object.id %}
            <template>
                <td id="shopping-inventory-{{ shopping_inventory.id }}-item-{{ shopping_item.id }}-done"
                    hx-swap-oob="true">
                    {% if shopping_item.done %}
                        <i class="bi bi-check-circle-fill state-done"></i>
                    {% else %}
                        <i class="bi bi-circle state-undone"></i>
                    {% endif %}
                </td>
            </template>
        {% endif %}
    {% endif %}
{% endspaceless %}