atoum/urls.py
from django.urls import path

from .views import (
    AssortmentAutocompleteView,
    AssortmentDetailView,
    AssortmentIndexView,
    CategoryAutocompleteView,
    CategoryDetailView,
    CategoryIndexView,
    ConsumableDetailView,
    ConsumableIndexView,
    DashboardView,
    DummyView,
    GlobalSearchView,
    ProductAutocompleteView,
    ProductDetailView,
    ProductIndexView,
    RecursiveTreeView,
    ShoppinglistDetailView,
    ShoppinglistIndexView,
    ShoppinglistToggleSelectionView,
    ShoppinglistManageProductView,
)


app_name = "atoum"


urlpatterns = [
    path("", DashboardView.as_view(), name="dashboard"),

    # Full recursive tree of everything
    path("tree/", RecursiveTreeView.as_view(), name="tree"),

    path(
        "consumables/",
        ConsumableIndexView.as_view(),
        name="consumable-index"
    ),
    path(
        "assortments/",
        AssortmentIndexView.as_view(),
        name="assortment-index"
    ),
    path(
        "categories/",
        CategoryIndexView.as_view(),
        name="category-index"
    ),
    path(
        "products/",
        ProductIndexView.as_view(),
        name="product-index"
    ),
    path(
        "consumables/<slug:slug>/",
        ConsumableDetailView.as_view(),
        name="consumable-detail"
    ),
    path(
        "consumables/<slug:consumable_slug>/<slug:assortment_slug>/",
        AssortmentDetailView.as_view(),
        name="assortment-detail"
    ),
    path(
        (
            "consumables/<slug:consumable_slug>/<slug:assortment_slug>/"
            "<slug:category_slug>/"
        ),
        CategoryDetailView.as_view(),
        name="category-detail"
    ),
    path(
        (
            "consumables/<slug:consumable_slug>/<slug:assortment_slug>/"
            "<slug:category_slug>/<slug:product_slug>/"
        ),
        ProductDetailView.as_view(),
        name="product-detail"
    ),

    # TODO: These are temporarily dummy views enabled to allow reversing until
    # they are implemented
    path(
        "brands/<slug:slug>/",
        DummyView.as_view(),
        name="brand-detail"
    ),

    # Shopping list parts
    path(
        "shopping/",
        ShoppinglistIndexView.as_view(),
        name="shopping-list-index"
    ),
    # TODO: Rename with "inventory" instead
    path(
        "shopping/close-selection/",
        ShoppinglistToggleSelectionView.as_view(),
        name="shopping-list-close-selection"
    ),
    path(
        "shopping/<int:pk>/",
        ShoppinglistDetailView.as_view(),
        name="shopping-list-detail"
    ),
    # TODO: Rename with "inventory" instead
    path(
        "shopping/<int:pk>/open-selection/",
        ShoppinglistToggleSelectionView.as_view(),
        name="shopping-list-open-selection"
    ),
    path(
        "shopping/<int:pk>/product/<int:product_id>/",
        ShoppinglistManageProductView.as_view(),
        name="shopping-list-product"
    ),

    # Autocomplete views for various models, only for staff users
    path(
        "autocomplete/assortments/",
        AssortmentAutocompleteView.as_view(),
        name="autocomplete-assortments",
    ),
    path(
        "autocomplete/categories/",
        CategoryAutocompleteView.as_view(),
        name="autocomplete-categories",
    ),
    path(
        "autocomplete/products/",
        ProductAutocompleteView.as_view(),
        name="autocomplete-products",
    ),

    # Search engine form and results
    path("search/", GlobalSearchView.as_view(), name="search-results"),
]

atoum/forms/shopping.py
from django import forms

from dal import autocomplete

from ..models import Product, Shopping, ShoppingItem


class ProductBreadcrumbChoiceField(forms.ModelChoiceField):
    """
    Customize product model choice field.
    """
    def label_from_instance(self, obj):
        """
        Display product parenting crumbs of a choice option.

        This label should be the same returned from
        ``ProductAutocompleteView.get_selected_result_label()``.
        """
        return obj.parenting_crumbs_html()


class ShoppingAdminForm(forms.ModelForm):
    class Meta:
        fields = "__all__"
        model = Shopping


class ShoppingItemInlineForm(autocomplete.FutureModelForm):
    class Meta:
        fields = "__all__"
        model = ShoppingItem

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        # Override Product model form field to customize option label and enable
        # DAL autocompletion
        self.fields["product"] = ProductBreadcrumbChoiceField(
            queryset=Product.objects.all().select_related(
                "category",
                "category__assortment",
                "category__assortment__consumable"
            ),
            required=True,
            blank=False,
            widget=autocomplete.ModelSelect2(
                url="atoum:autocomplete-products",
                attrs={"data-html": True},
            ),
        )

atoum/views/shopping.py
from django.conf import settings
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import RedirectURLMixin
from django.shortcuts import get_object_or_404
from django.http import HttpResponseRedirect, HttpResponseBadRequest, QueryDict
from django.views import View
from django.views.generic import TemplateView
from django.views.generic import ListView
from django.urls import reverse
from django.utils.translation import gettext_lazy as _

from ..models import Product, Shopping, ShoppingItem
from .mixins import AtoumBreadcrumMixin


class ShoppinglistIndexView(AtoumBreadcrumMixin, LoginRequiredMixin, ListView):
    """
    List of Shopping lists
    """
    model = Shopping
    template_name = "atoum/shopping/index.html"
    paginate_by = settings.ATOUM_SHOPPINGLIST_PAGINATION
    crumb_title = _("Shopping lists")
    crumb_urlname = "atoum:shopping-list-index"

    def get_queryset(self):
        # Append 'done' field over the common ordering fields so the undone lists
        # have higher priority
        ordering = ["done"] + self.model.COMMON_ORDER_BY
        return self.model.objects.order_by(*ordering)

    @property
    def crumbs(self):
        return [
            (
                ShoppinglistIndexView.crumb_title,
                reverse(ShoppinglistIndexView.crumb_urlname)
            ),
        ]


class ShoppinglistDetailView(AtoumBreadcrumMixin, LoginRequiredMixin, TemplateView):
    """
    Shopping list detail
    """
    model = Shopping
    template_name = "atoum/shopping/detail.html"
    context_object_name = "shopping_object"
    crumb_title = None  # No usage since title depends from object
    crumb_urlname = "atoum:shopping-list-detail"

    @property
    def crumbs(self):
        return [
            (
                ShoppinglistIndexView.crumb_title,
                reverse(ShoppinglistIndexView.crumb_urlname)
            ),
            (
                str(self.object),
                reverse(self.crumb_urlname, kwargs={
                    "pk": self.object.id,
                })
            ),
        ]

    def get_object(self):
        """
        Get the Shopping list object
        """
        return get_object_or_404(self.model, pk=self.kwargs.get("pk"))

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context.update({
            "object": self.object,
            self.context_object_name: self.object,
        })

        return context

    def get(self, request, *args, **kwargs):
        self.object = self.get_object()

        return super().get(request, *args, **kwargs)


class ShoppinglistToggleSelectionView(LoginRequiredMixin, RedirectURLMixin, View):
    """
    View to open or close a Shopping list for product selection.

    For opening it requires the shopping ID in "pk" argument from URL. For closing it
    does not require anything and just blindly purge the session variable.
    """
    model = Shopping
    raise_exception = True

    def get_object(self):
        """
        Get the Shopping list object
        """
        return get_object_or_404(self.model, pk=self.kwargs.get("pk"))

    def get(self, request, *args, **kwargs):
        self.next_page = reverse("atoum:dashboard")

        url = self.get_success_url()

        # If shopping id is given add it as opened in session
        if "pk" in self.kwargs:
            self.object = self.get_object()
            self.request.session["atoum_shopping_inventory"] = self.object.id
        # Else assume we have to close any opened shopping from session
        else:
            del self.request.session["atoum_shopping_inventory"]

        return HttpResponseRedirect(url)


class ShoppinglistManageProductView(LoginRequiredMixin, TemplateView):
    """
    View to add, edit or remove a product of a Shopping list.

    This has been done for usage from htmx so it won't return a proper HTML page
    document.
    """
    model = Shopping
    template_name = "atoum/shopping/manage_inventory.html"
    operation_name = None
    raise_exception = True

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context.update({
            "shopping_object": self.object,
            "product": self.product,
            "shopping_item": self.shopping_item,
            "operation": self.operation_name,
        })

        return context

    def parse_quantity(self):
        """
        Parse given quantity from POST arguments.

        Returns:
            integer: Parsed quantity if it is a valid integer else returns a null
                value.
        """
        try:
            quantity = int(self.request.POST.get("quantity", 1))
        except ValueError:
            return None

        if not quantity or quantity < 1:
            quantity = 0

        return quantity

    def delete_shopping_item(self):
        """
        Remove the given product item from the Shopping list.

        Returns:
            dict: Return dict with some values (id and quantity) from deleted object.
        """
        obj = get_object_or_404(
            ShoppingItem,
            shopping=self.object,
            product=self.product
        )

        # Memorize useful data from object because template still use it
        memorized = {"id": obj.id, "quantity": obj.quantity}
        # Finally deletes the item
        obj.delete()
        self.operation_name = "deletion"

        return memorized

    def update_or_create_shopping_item(self, quantity):
        """
        Update or create the ShoppingItem object and possibly set its quantity if not
        null.

        Arguments:
            quantity (integer): The quantity to apply on object. It must be a greater
                or equal to 1 else it would not do nothing (except getting existing
                item).

        Returns:
            atoum.models.ShoppingItem: Return the existing or created object if
                quantity is greater or equal to 1. Else it returns the item object if
                it already exists or a null value if it does not exists yet.
        """
        try:
            obj = ShoppingItem.objects.filter(
                shopping=self.object,
                product=self.product
            ).get()
        except ShoppingItem.DoesNotExist:
            if quantity:
                obj = ShoppingItem(
                    shopping=self.object,
                    product=self.product,
                    quantity=quantity
                )
                obj.full_clean()
                obj.save()
                self.operation_name = "addition"
            else:
                obj = None
        else:
            if quantity:
                obj.quantity = quantity
                obj.full_clean()
                obj.save()
                self.operation_name = "edition"

        return obj

    def patch_shopping_item(self, done=None):
        """
        Update attribute ``done`` of the Shopping item.
        """
        if done is None:
            return

        obj = get_object_or_404(
            ShoppingItem,
            shopping=self.object,
            product=self.product
        )

        # NOTE: We can use the update() method instead
        obj.done = done
        obj.save()

        self.object.update_shopping_done()

        self.operation_name = "patch_field_done"

        return obj

    def patch(self, request, *args, **kwargs):
        """
        PATCH verb allows to edit the ``done`` state.
        """
        self.object = get_object_or_404(self.model, pk=self.kwargs.get("pk"))
        self.product = get_object_or_404(Product, pk=self.kwargs.get("product_id"))

        data = QueryDict(self.request.body)

        done_value = (
            data.get("done") == "true"
            if data.get("done", None)
            else None
        )
        # Done field value is mandatory
        if done_value is None:
            return HttpResponseBadRequest()

        self.shopping_item = self.patch_shopping_item(done=done_value)

        return self.render_to_response(self.get_context_data(**kwargs))

    def delete(self, request, *args, **kwargs):
        """
        DELETE verb allows for deletion of an existing product item from a shopping
        list.

        Response will only contains the HTML for product controls for a creation.
        """
        self.object = get_object_or_404(self.model, pk=self.kwargs.get("pk"))
        self.product = get_object_or_404(Product, pk=self.kwargs.get("product_id"))

        self.shopping_item = self.delete_shopping_item()

        return self.render_to_response(self.get_context_data(**kwargs))

    def post(self, request, *args, **kwargs):
        """
        POST verb allows for creation or edition of a product item from a shopping list.

        If product is already an item of shopping list it is an edition and posted
        quantity will replace the previous value.

        Else if product is not in shopping list yet it is a creation and quantity will
        be set from posted value.

        Negative or null quantity is not allowed, it will return a HTTP 400 response.

        Response will contains the HTML for product controls and possibly the new item
        row to append to the shopping list component in case of a creation.
        """
        self.object = get_object_or_404(self.model, pk=self.kwargs.get("pk"))
        self.product = get_object_or_404(Product, pk=self.kwargs.get("product_id"))

        quantity = self.parse_quantity()
        if quantity is None:
            return HttpResponseBadRequest()

        # Proceed to operation
        self.shopping_item = self.update_or_create_shopping_item(quantity)
        return self.render_to_response(self.get_context_data(**kwargs))

    def get(self, request, *args, **kwargs):
        """
        GET verb is not supported.
        """
        return HttpResponseBadRequest()

atoum/templates/atoum/shopping/partials/list_status.html
{% load i18n %}{% spaceless %}
    {% if shopping_object.done %}
        <i class="bi bi-cart-check state-done"></i> {% translate "Done" %}
    {% elif shopping_inventory and shopping_inventory.id == shopping_object.id %}
        <i class="bi bi-cart-plus state-open"></i> {% translate "Open" %}
    {% else %}
        <i class="bi bi-cart2 state-todo"></i> {% translate "To do" %}
    {% endif %}
{% endspaceless %}

atoum/templates/atoum/shopping/partials/opened_list_item.html
{% load i18n %}{% spaceless %}
    {% comment %}
    Product item row exists in this partial template so it can be
    shared from both shopping list render and the shopping management view with
    htmx.

    It does not include HTML for "deletion" and "patch_field_done" operations since it
    is simple enough to be on its own apart in management template.
    {% endcomment %}
    {% if operation == "addition" %}
        <tbody hx-swap-oob="afterbegin:#shopping-inventory-{{ shopping_inventory.id }}-rows">
    {% endif %}

        <tr id="shopping-inventory-{{ shopping_inventory.id }}-item-{{ item.id }}"
            {% if operation == "edition" %} hx-swap-oob="true"{% endif %}
            {% if operation == "addition" or operation == "edition" %} class="bump"{% endif %}>
            <td class="quantity">{{ item.quantity }}</td>
            <td class="title">{{ item.product.title }}</td>
            <td class="done"
                id="shopping-inventory-{{ shopping_inventory.id }}-item-{{ item.id }}-done">
                {% if item.done %}
                    <i class="bi bi-check-circle-fill"></i>
                {% else %}
                    <i class="bi bi-circle"></i>
                {% endif %}
            </td>
        </tr>

    {% if operation == "addition" %}
        </tbody>
    {% endif %}
{% endspaceless %}

atoum/templates/atoum/shopping/partials/tag_opened_list.html
{% load i18n %}{% spaceless %}
    {% if shopping_inventory %}
        <div id="aside-shopping">
            <div class="head">
                <h3 class="title h6">
                    {% if shopping_inventory.done %}
                        <i class="bi bi-cart-check"></i>
                    {% else %}
                        <i class="bi bi-cart3"></i>
                    {% endif %}
                    {{ shopping_inventory }}
                </h3>

                <div class="controls btn-group" role="group" aria-label="Current shopping list controls">
                    <a href="{{ shopping_inventory.get_absolute_url }}"
                       class="btn cta-manage btn-outline-primary"
                       title="{% trans "Manage" %}"
                       aria-label="{% trans "Manage" %}">
                        <span>{% translate "Manage" %}</span>
                    </a>

                    <a href="{% url "atoum:shopping-list-close-selection" %}?next={{ request.path }}"
                       class="btn cta-disable btn-outline-primary"
                       title="{% trans "Disable" %}"
                       aria-label="{% trans "Disable" %}">
                        <span>{% translate "Disable" %}</span>
                    </a>

                    <button class="class-toggler toggler-enable btn btn-outline-primary"
                            type="button"
                            data-target="body"
                            data-target-css="shopping-inventory-opened"
                            aria-label="{% trans "Toggle shopping inventory" %}"
                            aria-expanded="false"></button>
                </div>
            </div>

            {% if shopping_inventory.current_items %}
                <table class="inventory table table-hover table-bordered" id="shopping-inventory-{{ shopping_inventory.id }}">
                    <thead>
                        <tr>
                            <th>{% translate "Quantity" %}</th>
                            <th>{% translate "Product" %}</th>
                            <th>{% translate "Done" %}</th>
                        </tr>
                    </thead>
                    <tbody id="shopping-inventory-{{ shopping_inventory.id }}-rows">
                        {% for item in shopping_inventory.current_items %}
                            {% include "atoum/shopping/partials/opened_list_item.html" with shopping_inventory=shopping_inventory item=item only %}
                        {% endfor %}
                    </tbody>
                </table>
            {% else %}
                <p class="inventory empty">{% translate "No products yet." %}</p>
            {% endif %}
        </div>
    {% endif %}
{% endspaceless %}

atoum/templates/atoum/shopping/partials/tag_shopping_aside_html.html
{% load i18n %}{% spaceless %}
    <div class="aside-shopping">
        <div class="head">
            <h3 class="title h6">
                {% if opened_shoppinglist.obj.done %}
                    <i class="bi bi-cart-check"></i>
                {% else %}
                    <i class="bi bi-cart3"></i>
                {% endif %}
                {{ opened_shoppinglist.obj }}
            </h3>

            <div class="controls btn-group btn-group-sm" role="group" aria-label="Current shopping list controls">
                <a href="{{ opened_shoppinglist.obj.get_absolute_url }}" class="btn btn-outline-primary">
                    {% translate "Show" %}
                </a>
                <a href="{% url "atoum:shopping-list-close-selection" %}?next={{ request.path }}" class="btn btn-outline-primary">
                    {% translate "Close" %}
                </a>
            </div>
        </div>

        {% comment %}<div class="d-flex justify-content-end">
            <div class="btn-group btn-group-sm" role="group" aria-label="Current shopping list controls">
                <button type="button" class="btn btn-outline-primary">{% translate "Save" %}</button>
            </div>
        </div>{% endcomment %}

        {% if opened_shoppinglist.items %}
            <table class="table table-hover table-bordered" id="shopping-list-{{ opened_shoppinglist.obj.id }}">
                <thead>
                    <tr>
                        <th>{% translate "Quantity" %}</th>
                        <th>{% translate "Product" %}</th>
                        <th>{% translate "Done" %}</th>
                    </tr>
                </thead>
                <tbody>
                    {% for item in opened_shoppinglist.items %}
                        {% include "atoum/shopping/partials/shopping_aside_product_item.html" with opened_shoppinglist=opened_shoppinglist item=item only %}
                    {% endfor %}
                </tbody>
            </table>
        {% else %}
            <p class="empty">{% translate "No products yet." %}</p>
        {% endif %}
    </div>
{% endspaceless %}