sandbox/accounts/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path

from .forms import AuthenticationForm


app_name = "accounts"


urlpatterns = [
    path(
        "login/",
        auth_views.LoginView.as_view(
            form_class=AuthenticationForm,
            template_name="accounts/login.html",
        ),
        name="login"
    ),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),
]

sandbox/styleguide/urls.py
from django.urls import path

from .views import StyleguideIndexView


app_name = "styleguide"


urlpatterns = [path("", StyleguideIndexView.as_view(), name="index")]

sandbox/urls.py
"""
URL Configuration for sandbox
"""
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import include, path


urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("sandbox.accounts.urls", namespace="accounts")),
    path("styleguide/", include("sandbox.styleguide.urls", namespace="styleguide")),
    path("", include("atoum.urls")),
]

# This is only needed when using runserver with settings "DEBUG" enabled
if settings.DEBUG:
    try:
        import debug_toolbar  # noqa: F401,F403
    except ImportError:
        pass
    else:
        urlpatterns.append(
            path("__debug__/", include("debug_toolbar.urls"))
        )

    urlpatterns = (
        urlpatterns +
        staticfiles_urlpatterns() +
        static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    )

sandbox/accounts/forms/authentication.py
from django.contrib.auth.forms import AuthenticationForm as BaseAuthenticationForm

from ..form_helpers import AuthenticationFormHelper


class AuthenticationForm(BaseAuthenticationForm):
    """
    Form to authenticate user.
    """

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.helper = AuthenticationFormHelper()

sandbox/styleguide/views.py
from django.conf import settings
from django.contrib.auth.mixins import LoginRequiredMixin

from py_css_styleguide.django.views import StyleguideViewMixin


class StyleguideIndexView(LoginRequiredMixin, StyleguideViewMixin):
    """
    Display styleguide from CSS manifest
    """

    template_name = "styleguide/index.html"
    manifest_css_filepath = settings.STYLEGUIDE_MANIFEST_PATH
    manifest_json_filepath = settings.STYLEGUIDE_DUMP_PATH
    save_dump = settings.STYLEGUIDE_SAVE_DUMP
    development_mode = settings.DEBUG

sandbox/templates/accounts/login.html
{% extends "skeleton.html" %}
{% load crispy_forms_tags i18n static %}
{% block header-title %}{% translate "Authentication" %} - {{ block.super }}{% endblock header-title %}

{% block body-container %}
{% spaceless %}
    <div class="layout-cover">
        {% include "partials/brand.html" %}

        <div class="page-content d-flex justify-content-center align-items-center">
            <div class="accounts-login-content">
                <h1>{% translate "Authentication" %}</h1>

                {% if next %}
                    {% if user.is_authenticated %}
                    <p>{% translate "Your account doesn't have access to this page. To proceed, please login with an account that has access." %}</p>
                    {% else %}
                    <p>{% translate "Please login to see this page." %}</p>
                    {% endif %}
                {% endif %}

                <form method="post" action="{% url 'accounts:login' %}"
                      id="accounts-login-form" class="needs-validation">
                    {% crispy form %}
                    <input type="hidden" name="next" value="{{ next }}">
                </form>
            </div>
        </div>
    </div>
{% endspaceless %}
{% endblock body-container %}

sandbox/templates/styleguide/base.html
{% extends "skeleton.html" %}
{% load static %}
{# djlint:off #}
{% block html-attrs %} id="sg-document"{% endblock html-attrs %}
{% block header-title %}Styleguide - {{ block.super }}{% endblock header-title %}
{# djlint:on #}
{% block metas-robot %}
    <meta name="robots" content="noindex, nofollow">
{% endblock metas-robot %}
{% block header-resource-extra %}
    <link rel="stylesheet" href="{% static "css/components/styleguide/layout.css" %}">
{% endblock header-resource-extra %}
{% block body-container %}
    <div id="sg-layout">
        <div id="sg-menu">
            <a href="./" class="brand">
                <h1 class="h3 sg-neutral-font">Styleguide</h1>
            </a>
            <ul class="sg-menu" id="sg-menu-main">
            </ul>
        </div>
        <div id="sg-content">
            {% include "partials/color_mode_toggler.html" %}
            {% block styleguide-content %}
            {% endblock styleguide-content %}
        </div>
    </div>
{% endblock body-container %}

sandbox/templates/styleguide/index.html
{% extends "styleguide/base.html" %}
{% block styleguide-content %}
    {% if styleguide.status == "failed" %}
        <div class="container-xl">
            <div class="alert alert-warning" role="alert">
                <h2 class="sg-neutral-font">Error</h2>
                <p>{{ styleguide.loading_error|safe }}</p>
            </div>
        </div>
    {% else %}
        <div id="sg-render">
            {% comment %}NOTE: Uncomment this to display the JSON Manifest{% endcomment %}
            {% comment %}<div class="container-xl"><h2 class="section-title sg-anchor" id="debug">Manifest JSON</h2><pre>{{ styleguide.to_json|safe }}</pre></div>{% endcomment %}
            <div class="container-xl">
                <p class="text-end">
                    <span class="badge bg-dark">{{ styleguide.status }}</span>
                    <span class="badge bg-light text-dark">Built on {{ styleguide.metas.created }}</span>
                </p>
            </div>
            {% include "styleguide/parts/typography.html" %}
            {% include "styleguide/parts/colors.html" %}
            {% include "styleguide/parts/icons.html" %}
            {% include "styleguide/parts/buttons.html" %}
            {% include "styleguide/parts/spacing.html" %}
            {% include "styleguide/parts/grid.html" %}
            {% include "styleguide/parts/blocks.html" %}
        </div>
    {% endif %}
{% endblock styleguide-content %}
{% block body-javascript-extra %}
    <script>
(function () {
    'use strict'

    //
    // Create menu item link item with optional submenu for children links
    //
    function createMenuItem(key, heading) {
        // Create menu item
        let $menu_item = document.createElement("li");
        let $item_link = document.createElement("a");
        $item_link.setAttribute("href", "#" + key);
        $item_link.className = "menu-item";
        $item_link.textContent = heading["name"];

        // Create item link in menu item
        $menu_item.appendChild($item_link);

        // Create submenu if item has children
        if (Object.keys(heading["children"]).length > 1) {
            let $submenu = document.createElement("ul");
            $submenu.className = "sg-menu";
            // Get all submenu children items
            for (var prop in heading["children"]) {
                $submenu.appendChild(
                    createMenuItem(prop, heading["children"][prop])
                );
            }
            $menu_item.appendChild($submenu);
        }

        return $menu_item;
    }

    // Create a tree of anchors to build the navigation.
    // This only works on anchor with "sg-anchor" class and on two levels
    // maximum. First level is always a single word and second level starts with its
    // parent id then a "-" separator then the word(s).
    let anchorMap = {};
    document.querySelectorAll('#sg-content .sg-anchor').forEach(function (heading) {
        let parts = heading.id.split('-');

        // If heading has more than one part, search through root headings to find
        // parent and add heading to its parent children.
        if (parts.length > 1 && Object.keys(anchorMap).indexOf(parts[0]) > -1) {
            anchorMap[parts[0]]["children"][heading.id] = {
                "name": heading.textContent,
                "children": {},
            };
        // Else assume it's a root
        } else {
            anchorMap[heading.id] = {
                "name": heading.textContent,
                "children": {},
            };
        }
    });

    let $styleguide_main_menu = document.getElementById('sg-menu-main');
    for (var prop in anchorMap) {
        $styleguide_main_menu.appendChild(
            createMenuItem(prop, anchorMap[prop])
        );
    }
})()
    </script>
{% endblock body-javascript-extra %}

sandbox/templates/styleguide/parts/blocks.html
<div class="container-xl mb-5">
    <h2 class="section-title sg-anchor" id="blocks">Blocks</h2>
    <p class="lead">Basic usage demonstration with all class modifiers for spacing and color schemes.</p>
</div>
<div id="sg-blocks">
    <hr>
    <div class="block">
        <div class="container-xl">
            <p class="h1">Default block</p>
            {% include "styleguide/parts/inline_markup.html" %}
            {% lorem 2 p random %}
        </div>
    </div>
    <hr>
    <div class="block unpadded">
        <div class="container-xl">
            <p class="h1">unpadded</p>
            {% include "styleguide/parts/inline_markup.html" %}
            {% lorem 2 p random %}
        </div>
    </div>
    {% for k in styleguide.bt_spaces %}
        <hr>
        <div class="block {{ k }}">
            <div class="container-xl">
                <p class="h1">{{ k }}</p>
                {% include "styleguide/parts/inline_markup.html" %}
                {% lorem 2 p random %}
            </div>
        </div>
    {% endfor %}
    {% if styleguide.bb_schemes_neutral %}
        <hr>
        <div class="block {{ styleguide.bb_schemes_neutral }}">
            <div class="container-xl">
                <p class="h1">{{ styleguide.bb_schemes_neutral }}</p>
                <p class="h2">Heading level 2</p>
                <p class="h3">Heading level 3</p>
                <p class="h4">Heading level 4</p>
                <p class="h5">Heading level 5</p>
                <p class="h6">Heading level 6</p>
                {% include "styleguide/parts/inline_markup.html" %}
                {% lorem 1 p random %}
            </div>
        </div>
    {% endif %}
    {% for k in styleguide.bb_schemes %}
        <hr>
        <div class="block {{ k }}">
            <div class="container-xl">
                <p class="h1">{{ k }}</p>
                <p class="h2">Heading level 2</p>
                <p class="h3">Heading level 3</p>
                <p class="h4">Heading level 4</p>
                <p class="h5">Heading level 5</p>
                <p class="h6">Heading level 6</p>
                {% include "styleguide/parts/inline_markup.html" %}
                {% lorem 1 p random %}
            </div>
        </div>
    {% endfor %}
</div>

sandbox/templates/styleguide/parts/buttons.html
{% with sample_icon=styleguide.st_icon_glyphs.0 %}
    <div class="buttons-sample container-xl mb-5">
        <h2 class="section-title sg-anchor" id="buttons">Buttons</h2>
        <div class="row align-items-start g-3 py-3">
            <h3 class="part-title sg-anchor" id="buttons-theme">Theme</h3>
            <p class="lead col-12">Available button theme colors usable as class helpers.</p>
            <div class="col-12 col-lg-3 demo-content">
                <button type="button" class="btn">Default</button>
            </div>
            <div class="col-12 col-lg-3 demo-content">
                <button type="button" class="btn btn-link">Link</button>
            </div>
            {% for k,v in styleguide.bt_theme.items %}
                <div class="col-12 col-lg-3 demo-content">
                    <button type="button" class="btn btn-{{ k }}">btn-{{ k }}</button>
                </div>
            {% endfor %}
        </div>
        <hr class="part-divider">
        <div class="row align-items-start g-3 py-3">
            <h3 class="part-title sg-anchor" id="buttons-sizes">Sizes</h3>
            <p class="lead col-12">Available button sizes usable as class helpers.</p>
            <div class="col-12 col-lg-3 demo-content">
                <button type="button" class="btn btn-primary">Default</button>
            </div>
            {% for k in styleguide.bt_button_sizes %}
                <div class="col-12 col-lg-3 demo-content">
                    <button type="button" class="btn btn-primary btn-{{ k }}">btn-{{ k }}</button>
                </div>
            {% endfor %}
        </div>
        <hr class="part-divider">
        <div class="row align-items-start g-3 py-3">
            <h3 class="part-title sg-anchor" id="buttons-spot">Spot</h3>
            <p class="lead col-12">A button variant to get a correct round button with a single class helper.</p>
            <div class="col-12 col-lg-3 demo-content">
                <a href="#" class="btn btn-primary">
                    <span class="visually-hidden">Accessible text</span>
                    <i class="bi bi-{{ sample_icon }}" aria-hidden="true"></i>
                </a>
                &nbsp;
                <a href="#" class="btn btn-primary spot">
                    <span class="visually-hidden">Accessible text</span>
                    <i class="bi bi-{{ sample_icon }}" aria-hidden="true"></i>
                </a>
                {% for k in styleguide.bt_button_sizes %}
                    &nbsp;
                    <a href="#" class="btn btn-primary btn-{{ k }} spot">
                        <span class="visually-hidden">Accessible text</span>
                        <i class="bi bi-{{ sample_icon }}" aria-hidden="true"></i>
                    </a>
                {% endfor %}
            </div>
            <div class="col-12 col-lg-3 demo-content">
                <button type="button" class="btn btn-primary spot">spot</button>
            </div>
            <div class="col-12 col-lg-3 demo-content">
                <a href="#" class="btn btn-primary spot">
                    <span class="visually-hidden">Accessible text</span>
                    <i class="bi bi-{{ sample_icon }}" aria-hidden="true"></i> spot
                </a>
            </div>
            <div class="col-12 col-lg-3 demo-content">
                <button type="button" class="btn btn-primary spot bi bi-{{ sample_icon }}">spot</button>
            </div>
        </div>

        {% comment %}NOTE: Disabled because i currently lost the related Sass source..{% endcomment %}
        {% comment %}<hr class="part-divider">
        <div class="row align-items-start g-3 py-3">
            <h3 class="part-title sg-anchor" id="buttons-toolbar">Toolbar</h3>
            <p class="lead">
                Alike the Bootstrap component "Button group" but do not stack horizontally and include an optional group divider.
            </p>
            <p>
                Unlike the "Button group", you can't define button feature from group container, you need to explicitely do it on each button.
            </p>
            <p>
                Default divider color is black, use a border color utility class (like <code>border-white</code>) to change it.
            </p>
            <p>
                Use optional breakpoint classes (<code>break-md</code>, <code>break-lg</code>, etc..) to define when the groups vertically stack.
            </p>
            <div class="col-12 col-lg-6 demo-content">
                <div class="button-toolbar break-md"
                     role="toolbar"
                     aria-label="A button toolbar">
                    <div class="group" role="group" aria-label="First group">
                        <a href="#" class="btn btn-primary">1.1</a>
                        <a href="#" class="btn btn-primary">1.2</a>
                    </div>
                    <div class="group" role="group" aria-label="Second group">
                        <a href="#" class="btn btn-primary">2.1</a>
                        <a href="#" class="btn btn-primary">2.2</a>
                    </div>
                </div>
            </div>
            <div class="col-12 col-lg-6 demo-content">
                <div class="button-toolbar break-md"
                     role="toolbar"
                     aria-label="A button toolbar">
                    <div class="group divider" role="group" aria-label="First group">
                        <a href="#" class="btn btn-primary spot">
                            <span class="visually-hidden">Accessible text</span>
                            <i class="bi bi-{{ sample_icon }}" aria-hidden="true"></i>
                        </a>
                        <a href="#" class="btn btn-primary spot">
                            <span class="visually-hidden">Accessible text</span>
                            <i class="bi bi-{{ sample_icon }}" aria-hidden="true"></i>
                        </a>
                    </div>
                    <div class="group" role="group" aria-label="Second group">
                        <button class="btn btn-primary spot btn-lg bi bi-{{ sample_icon }}">Text</button>
                    </div>
                </div>
            </div>
            <div class="col-12 col-lg-6 demo-content">
                <div class="button-toolbar break-md"
                     role="toolbar"
                     aria-label="A button toolbar">
                    <div class="group divider" role="group" aria-label="First group">
                        <a href="#" class="btn btn-primary spot">
                            <span class="visually-hidden">Accessible text</span>
                            <i class="bi bi-{{ sample_icon }}" aria-hidden="true"></i>
                        </a>
                        <a href="#" class="btn btn-primary spot">
                            <span class="visually-hidden">Accessible text</span>
                            <i class="bi bi-{{ sample_icon }}" aria-hidden="true"></i>
                        </a>
                        <a href="#" class="btn btn-primary">
                            <span class="visually-hidden">Accessible text</span>
                            <i class="bi bi-{{ sample_icon }}" aria-hidden="true"></i>
                        </a>
                    </div>
                    <div class="group" role="group" aria-label="Second group">
                        <button class="btn btn-primary btn-lg bi bi-{{ sample_icon }}">Text</button>
                    </div>
                </div>
            </div>
            <div class="col-12 col-lg-6 demo-content">
                <div class="button-toolbar break-md"
                     role="toolbar"
                     aria-label="A button toolbar">
                    <div class="group divider" role="group" aria-label="First group">
                        <a href="#" class="btn btn-primary">
                            <span class="visually-hidden">Accessible text</span>
                            <i class="bi bi-{{ sample_icon }}" aria-hidden="true"></i>
                        </a>
                        <a href="#" class="btn btn-primary">
                            <span class="visually-hidden">Accessible text</span>
                            <i class="bi bi-{{ sample_icon }}" aria-hidden="true"></i>
                        </a>
                        <a href="#" class="btn btn-primary">
                            <span class="visually-hidden">Accessible text</span>
                            <i class="bi bi-{{ sample_icon }}" aria-hidden="true"></i>
                        </a>
                    </div>
                    <div class="group" role="group" aria-label="Second group">
                        <button class="btn btn-primary spot btn-lg bi bi-{{ sample_icon }}">Text</button>
                    </div>
                </div>
            </div>
            <div class="col-12 col-lg-6 demo-content">
                <div class="button-toolbar break-md"
                     role="toolbar"
                     aria-label="A button toolbar">
                    <div class="group divider border-danger"
                         role="group"
                         aria-label="First group">
                        <a href="#" class="btn spot btn-outline-primary">
                            <span class="visually-hidden">Accessible text</span>
                            <i class="bi bi-{{ sample_icon }}" aria-hidden="true"></i>
                        </a>
                        <a href="#" class="btn spot btn-outline-primary">
                            <span class="visually-hidden">Accessible text</span>
                            <i class="bi bi-{{ sample_icon }}" aria-hidden="true"></i>
                        </a>
                    </div>
                    <div class="group" role="group" aria-label="Second group">
                        <button class="btn btn-primary btn-lg bi bi-{{ sample_icon }}">Text</button>
                    </div>
                </div>
            </div>
        </div>{% endcomment %}

        {% comment %}NOTE: Disabled because it is not actually compatible with Bootstrap Icons{% endcomment %}
        {% comment %}<hr class="part-divider">
        <div class="row align-items-start g-3 py-3">
            <h3 class="part-title sg-anchor" id="buttons-cta">CTA</h3>
            <p class="lead col-12">
                Adopt spacing, size and color variants from Button but without default
                border and enforce block flow.
            </p>
            <div class="col-12 col-lg-3 demo-content">
                <a href="#" class="cta cta-primary">Default</a>
            </div>
            {% for k in styleguide.bt_button_sizes %}
                <div class="col-12 col-lg-3 demo-content">
                    <a href="#" class="cta cta-{{ k }} cta-primary">cta-{{ k }}</a>
                </div>
            {% endfor %}
            <div class="col-12 col-lg-3 demo-content">
                <a href="#" class="cta cta-primary">cta-primary</a>
            </div>
            <div class="col-12 col-lg-3 demo-content">
                <a href="#" class="cta cta-primary">
                    <i class="bi bi-{{ sample_icon }} icon-wide" aria-hidden="true"></i>
                    cta-primary
                </a>
            </div>
            <div class="col-12 col-lg-3 demo-content">
                <a href="#" class="cta cta-outline-primary">
                    <i class="bi bi-{{ sample_icon }} icon-wide" aria-hidden="true"></i>
                    cta-outline-primary
                </a>
            </div>
            <div class="col-12 col-lg-3 demo-content">
                <a href="#" class="cta spot cta-primary bi bi-{{ sample_icon }} icon-wide">spot</a>
            </div>
            <div class="col-12 col-lg-3 demo-content">
                <a href="#" class="cta spot cta-primary">
                    <i class="bi bi-{{ sample_icon }} icon-wide" aria-hidden="true"></i>
                </a>
            </div>
        </div>{% endcomment %}
    </div>
{% endwith %}

sandbox/templates/styleguide/parts/colors.html
<div class="colors-sample container-xl mb-5">
    <h2 class="section-title sg-anchor" id="colors">Colors</h2>

    <div class="palette row align-items-start g-3 py-3">
        <h3 class="part-title sg-anchor" id="colors-palette">Palette</h3>

        <p class="lead col-12">Available color names usable as Sass variables.</p>
        {% for k,v in styleguide.bt_palette.items %}
            <div class="col-12 col-md-6 col-lg-3 col-xl-2">
                <div class="card">
                    <div class="palette-color card-img-top" style="background: {{ v }}">
                        <span>${{ k }}</span>
                    </div>
                    <div class="card-body">
                        <p class="card-title" title="{{ v }}">{{ v }}</p>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>

    <hr class="part-divider">

    <div class="palette row align-items-start g-3 py-3">
        <h3 class="part-title sg-anchor" id="colors-themes">Themes</h3>

        <p class="lead col-12">Available theme colors usable as Sass variables and class modifiers on Bootstrap components.</p>
        {% for k,v in styleguide.bt_theme.items %}
            <div class="col-12 col-md-6 col-lg-3 col-xl-2">
                <div class="card">
                    <div class="palette-color card-img-top" style="background: {{ v }}">
                        <span class="font-monospace">{{ k }}</span>
                    </div>
                    <div class="card-body">
                        <p class="card-title" title="{{ v }}">{{ v }}</p>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>

    <hr class="part-divider">

    <div class="palette row align-items-start g-3 py-3">
        <h3 class="part-title sg-anchor" id="colors-schemes">Schemes</h3>

        <p class="lead col-12">Built schemes from themes.</p>
        {% for k,v in styleguide.bt_theme.items %}
            <div class="col-12 col-md-6 col-lg-3 col-xl-2">
                <div class="card text-bg-{{ k }}">
                    <div class="card-header">
                        <strong>{{ k|capfirst }}</strong>
                    </div>
                    <div class="card-body">
                        <small class="font-monospace">.text-bg-{{ k }}</small>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>

    <hr class="part-divider">

    <div class="row align-items-start g-3 py-3">
        <h3 class="part-title sg-anchor" id="colors-text-colors">Text colors</h3>

        <p class="lead col-12">Available theme colors for texts usable as class helpers.</p>
        {% for k,v in styleguide.bt_theme.items %}
            <div class="col-12 col-lg-6 demo-content">
                <p class="text-{{ k }}">
                    <b class="class-name">text-{{ k }}</b> {% lorem 3 w random %}
                </p>
            </div>
        {% endfor %}
    </div>
</div>

sandbox/templates/styleguide/parts/grid.html
<div class="grid-sample container-xl mb-5">
    <h2 class="section-title sg-anchor" id="grid">Grid</h2>
    <p class="lead">Basic demonstration of available grid column sizes.</p>
    <div class="row align-items-start g-3 p-2">
        {% for _ in ''|center:styleguide.bt_grid_columns %}
            <div class="col-{{ forloop.counter }}">
                <div class="px-2 py-1 border bg-light cell-class font-monospace">col-{{ forloop.counter }}</div>
            </div>
        {% endfor %}
    </div>
</div>

sandbox/templates/styleguide/parts/icons.html
<div class="container-xl mb-5">
    <h2 class="section-title sg-anchor" id="icons">Icons</h2>

    <div class="glyph-palette row align-items-start g-3 p-2">

        <h3 class="part-title sg-anchor" id="icons-glyphs">Glyphs</h3>
        <p class="lead col-12">Available icon glyphs usable as class helpers or Sass variables.</p>
        {% for k in styleguide.st_icon_glyphs %}
            <div class="col-12 col-md-6 col-lg-3 col-xl-1">
                <div class="card">
                    <div class="visual big card-img-top">
                        <i class="bi bi-{{ k }}"></i>
                    </div>
                    <div class="card-body demo-content">
                        <p class="card-title font-monospace">{{ k }}</p>
                        <p class="font-monospace">${{ k }}</p>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>

    <hr class="part-divider">

    {% with sample_icon=styleguide.st_icon_glyphs.0 %}
        <div class="glyph-palette row align-items-start g-3 p-2">
            <h3 class="part-title sg-anchor" id="icons-sizes">Sizes</h3>
            <p class="lead col-12">Available icon sizes usable as class helpers.</p>
            {% for k,v in styleguide.bb_icon_sizes.items %}
                <div class="col-12 col-md-6 col-lg-3 col-xl-2">
                    <div class="card">
                        <div class="visual card-img-top">
                            <i class="bi bi-{{ sample_icon }} icon-{{ k }}"></i>
                        </div>
                        <div class="card-body demo-content">
                            <p class="card-title font-monospace">icon-{{ k }}</p>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>

        <hr class="part-divider">

        <div class="glyph-palette row align-items-start g-3 p-2">
            <h3 class="part-title sg-anchor" id="icons-usages">Usage</h3>
            <p class="lead col-12">Basic usage demonstration in various elements.</p>

            <div class="col-12 col-md-6 col-lg-3 col-xl-2">
                <div class="card">
                    <div class="visual card-img-top">
                        <i class="bi bi-{{ sample_icon }}" aria-hidden="true"></i>
                    </div>
                    <div class="card-body demo-content">
                        <p class="card-title">Alone</p>
                    </div>
                </div>
            </div>

            <div class="col-12 col-md-6 col-lg-3 col-xl-2">
                <div class="card">
                    <div class="visual card-img-top">
                        Lorem <i class="bi bi-{{ sample_icon }}" aria-hidden="true"></i> ipsum salace.
                    </div>
                    <div class="card-body demo-content">
                        <p class="card-title">In a paragraph</p>
                    </div>
                </div>
            </div>

            <div class="col-12 col-md-6 col-lg-3 col-xl-2">
                <div class="card">
                    <div class="visual card-img-top">
                        <button class="btn btn-primary bi bi-{{ sample_icon }}">Foobar</button>
                    </div>
                    <div class="card-body demo-content">
                        <p class="card-title">In a text button</p>
                    </div>
                </div>
            </div>

            <div class="col-12 col-md-6 col-lg-3 col-xl-2">
                <div class="card">
                    <div class="visual card-img-top">
                        <button class="btn btn-primary">
                            <span class="visually-hidden">Accessible text</span>
                            <i class="bi bi-{{ sample_icon }}" aria-hidden="true"></i>
                        </button>
                    </div>
                    <div class="card-body demo-content">
                        <p class="card-title">In a button</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endwith %}

sandbox/templates/styleguide/parts/inline_markup.html
<p>
    Suspendisse <b>bold</b> mauris, auctor <strong>strong</strong> pretium ac, <i>italic</i> eu mauris. Donec in <em>emphased</em> tortor. Duis <small>small</small> orci sit amet justo <a href="">a link</a> vestibulum. Vivamus commodo <code>some code</code> arcu elit.
</p>