atoum/urls.py
from django.urls import path

from .views import (
    AssortmentAutocompleteView,
    AssortmentDetailView,
    AssortmentIndexView,
    CategoryAutocompleteView,
    CategoryDetailView,
    CategoryIndexView,
    ConsumableDetailView,
    ConsumableIndexView,
    DashboardView,
    DummyView,
    GlobalSearchView,
    ProductAutocompleteView,
    ProductDetailView,
    ProductIndexView,
    RecursiveTreeView,
    ShoppinglistDetailView,
    ShoppinglistIndexView,
    ShoppinglistToggleSelectionView,
    ShoppinglistManageProductView,
)


app_name = "atoum"


urlpatterns = [
    path("", DashboardView.as_view(), name="dashboard"),

    # Full recursive tree of everything
    path("tree/", RecursiveTreeView.as_view(), name="tree"),

    path(
        "consumables/",
        ConsumableIndexView.as_view(),
        name="consumable-index"
    ),
    path(
        "assortments/",
        AssortmentIndexView.as_view(),
        name="assortment-index"
    ),
    path(
        "categories/",
        CategoryIndexView.as_view(),
        name="category-index"
    ),
    path(
        "products/",
        ProductIndexView.as_view(),
        name="product-index"
    ),
    path(
        "consumables/<slug:slug>/",
        ConsumableDetailView.as_view(),
        name="consumable-detail"
    ),
    path(
        "consumables/<slug:consumable_slug>/<slug:assortment_slug>/",
        AssortmentDetailView.as_view(),
        name="assortment-detail"
    ),
    path(
        (
            "consumables/<slug:consumable_slug>/<slug:assortment_slug>/"
            "<slug:category_slug>/"
        ),
        CategoryDetailView.as_view(),
        name="category-detail"
    ),
    path(
        (
            "consumables/<slug:consumable_slug>/<slug:assortment_slug>/"
            "<slug:category_slug>/<slug:product_slug>/"
        ),
        ProductDetailView.as_view(),
        name="product-detail"
    ),

    # TODO: These are temporarily dummy views enabled to allow reversing until
    # they are implemented
    path(
        "brands/<slug:slug>/",
        DummyView.as_view(),
        name="brand-detail"
    ),

    # Shopping list parts
    path(
        "shopping/",
        ShoppinglistIndexView.as_view(),
        name="shopping-list-index"
    ),
    # TODO: Rename with "inventory" instead
    path(
        "shopping/close-selection/",
        ShoppinglistToggleSelectionView.as_view(),
        name="shopping-list-close-selection"
    ),
    path(
        "shopping/<int:pk>/",
        ShoppinglistDetailView.as_view(),
        name="shopping-list-detail"
    ),
    # TODO: Rename with "inventory" instead
    path(
        "shopping/<int:pk>/open-selection/",
        ShoppinglistToggleSelectionView.as_view(),
        name="shopping-list-open-selection"
    ),
    path(
        "shopping/<int:pk>/product/<int:product_id>/",
        ShoppinglistManageProductView.as_view(),
        name="shopping-list-product"
    ),

    # Autocomplete views for various models, only for staff users
    path(
        "autocomplete/assortments/",
        AssortmentAutocompleteView.as_view(),
        name="autocomplete-assortments",
    ),
    path(
        "autocomplete/categories/",
        CategoryAutocompleteView.as_view(),
        name="autocomplete-categories",
    ),
    path(
        "autocomplete/products/",
        ProductAutocompleteView.as_view(),
        name="autocomplete-products",
    ),

    # Search engine form and results
    path("search/", GlobalSearchView.as_view(), name="search-results"),
]

atoum/views/dashboard.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import TemplateView
from django.urls import reverse
from django.utils.translation import gettext_lazy as _

from ..models import Assortment, Category, Consumable, Product
from .mixins import AtoumBreadcrumMixin


class DashboardView(AtoumBreadcrumMixin, LoginRequiredMixin, TemplateView):
    """
    Catalog dashboard view

    .. todo::
        This should list:

        * Catalog models
        * open shopping lists
        * stock resume

    """
    template_name = "atoum/dashboard.html"
    crumb_title = _("Dashboard")
    crumb_urlname = "atoum:dashboard"

    @property
    def crumbs(self):
        return [
            (self.crumb_title, reverse(self.crumb_urlname)),
        ]

    def get_consumable_queryset(self):
        """
        Build consumable queryset.
        """
        qs = Consumable.objects.all().order_by(*Consumable.COMMON_ORDER_BY)

        return qs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        context.update({
            "consumable_count": Consumable.objects.all().count(),
            "assortment_count": Assortment.objects.all().count(),
            "category_count": Category.objects.all().count(),
            "product_count": Product.objects.all().count(),
        })

        return context

atoum/views/dummy.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import TemplateView


class DummyView(LoginRequiredMixin, TemplateView):
    """
    Temporary dummy view that show nothing. Used for get_absolute_url from models until
    their detail view has been done.
    """
    template_name = "atoum/dummy.html"

atoum/templates/atoum/base.html
{% extends "skeleton.html" %}
{% load atoum i18n %}

{% block body-classes %}{% if shopping_inventory %} shopping-inventory-enabled{% endif %}{% endblock body-classes %}

{% block content-classes %}{% if shopping_inventory %} splitted{% endif %}{% endblock content-classes %}

{% block content %}
    {% block app_content %}{% endblock app_content %}
{% endblock content %}

{% block body-attrs %} hx-headers='{"x-csrftoken": "{{ csrf_token }}"}'{% endblock body-attrs %}

{% block content-sidebar %}{% spaceless %}
    {% if shopping_inventory %}
        <div class="aside-content">
            {% shopping_list_html %}
        </div>
    {% endif %}
{% endspaceless %}{% endblock content-sidebar %}

atoum/templates/atoum/dashboard.html
{% extends "atoum/base.html" %}
{% load i18n %}
{% block header-title %}{% translate "Dashboard" %} - {{ block.super }}{% endblock header-title %}

{% block title-content %}{% spaceless %}
    <h1>{% translate "Dashboard" %}</h1>
{% endspaceless %}{% endblock title-content %}

{% block app_content %}{% spaceless %}
    <div class="dashboard">
        <h2 class="mb-4">{% translate "Catalog" %}</h2>

        <div class="features grid">
            <a class="item" href="{% url "atoum:consumable-index" %}">
                <div class="cover text-bg-consumable">
                    <i class="icon bi bi-boxes"></i>
                </div>
                <div class="body">
                    <span class="number">{{ consumable_count }}</span>
                    <span class="text">{% translate "Consumables" %}</span>
                </div>
            </a>

            <a class="item" href="{% url "atoum:assortment-index" %}">
                <div class="cover text-bg-assortment">
                    <i class="icon bi bi-stack"></i>
                </div>
                <div class="body">
                    <span class="number">{{ assortment_count }}</span>
                    <span class="text">{% translate "Assortments" %}</span>
                </div>
            </a>

            <a class="item" href="{% url "atoum:category-index" %}">
                <div class="cover text-bg-category">
                    <i class="icon bi bi-tags"></i>
                </div>
                <div class="body">
                    <span class="number">{{ category_count }}</span>
                    <span class="text">{% translate "Categories" %}</span>
                </div>
            </a>

            <a class="item" href="{% url "atoum:product-index" %}">
                <div class="cover text-bg-product">
                    <i class="icon bi bi-archive"></i>
                </div>
                <div class="body">
                    <span class="number">{{ product_count }}</span>
                    <span class="text">{% translate "Products" %}</span>
                </div>
            </a>
        </div>
    </div>
{% endspaceless %}{% endblock app_content %}

atoum/templates/atoum/dummy.html
{% extends "atoum/base.html" %}
{% load i18n %}
{% block header-title %}{% translate "Todo" %} - {{ block.super }}{% endblock header-title %}

{% block title-content %}{% spaceless %}
    <h1>{% translate "Todo" %}</h1>
{% endspaceless %}{% endblock title-content %}

{% block app_content %}{% spaceless %}
<div>
    <p>Nothing here.</p>
</div>
{% endspaceless %}{% endblock app_content %}

atoum/templates/atoum/pagination.html
{% load atoum i18n %}{% spaceless %}{% if paginator and paginator.num_pages > 1 %}
    <nav aria-label="{% trans "Pagination" %}">
        <ul class="pagination justify-content-center mt-3">
            {% for page_num in paginator.page_range %}
                <li class="page-item{% if page_num == page_obj.number %} active{% endif %}"
                    {% if page_num == page_obj.number %} aria-current="page"{% endif %}>
                    <a class="page-link" href="{% querystring page=page_num %}">{{ page_num }}</a>
                </li>
            {% endfor %}
        </ul>
    </nav>
{% endif %}{% endspaceless %}

atoum/templates/atoum/recursivetree.html
{% extends "atoum/base.html" %}
{% load i18n %}

{% block title-content %}{% spaceless %}
    <h1>{% translate "Tree" %}</h1>
{% endspaceless %}{% endblock title-content %}

{% block app_content %}{% spaceless %}
<div class="recursive-tree-page">
    <div class="mb-5">
        <h2 class="fs-5">Légende</h2>
        <p>
            <span class="badge text-bg-success fs-4">
                <i class="bi bi-boxes"></i> Consommable
            </span>&nbsp;-
            <span class="badge text-bg-primary rounded-pill fs-5">
                <i class="bi bi-stack"></i> Gamme
            </span>&nbsp;-
            <span class="badge text-bg-warning fs-6">
                <i class="bi bi-tags"></i> Categorie
            </span>&nbsp;-
            <span class="text-bg-light">
                <i class="bi bi-archive"></i> Produit
            </span>
        </p>
    </div>

    <hr>
    <div class="mb-5">
        <h2>Données</h2>
        <ul class="tree consumable-list">
            {% for consumable in object_list %}
                <li>
                    <span class="badge text-bg-success fs-4">{{ consumable.title }}</span>

                    {% with assortments=consumable.get_assortments %}
                        {% if assortments %}
                        <ul class="assortment-list my-2">
                            {% for assortment in assortments %}
                            <li class="mb-2">
                                <span class="badge rounded-pill text-bg-primary fs-5">{{ assortment.title }}</span>

                                {% with categories=assortment.get_categories %}
                                    {% if categories %}
                                    <ul class="category-list my-1">
                                        {% for category in categories %}
                                        <li class="mb-1">
                                            <span class="badge text-bg-warning fs-6">{{ category.title }}</span>

                                            {% with products=category.get_products %}
                                                {% if products %}
                                                <ul class="product-list my-1">
                                                    {% for product in products %}
                                                    <li class="mb-1">
                                                        {{ product.title }}
                                                    </li>
                                                    {% endfor %}
                                                </ul>
                                                {% endif %}
                                            {% endwith %}
                                        </li>
                                        {% endfor %}
                                    </ul>
                                    {% endif %}
                                {% endwith %}
                            </li>
                            {% endfor %}
                        </ul>
                        {% endif %}
                    {% endwith %}
                </li>
            {% empty %}
                <li>{% translate "No consumable yet." %}</li>
            {% endfor %}
        </ul>
    <div>
</div>
{% endspaceless %}{% endblock app_content %}